apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytomcat
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      name: mytomcat-app
      labels:
        app: myapp
    spec:
      containers:
        - name: mytomcat-container
          image: ommaxyl/mytomcat:2
          ports:
            - containerPort: 8080


    
